### ISSUE TITLE
Title/description for nested focus

### ISSUE THREAD

**Issue by mertenssander** [mertenssander/postco#22]
Hi @basharmsen ,
I just pulled the latest commit (and published on the public dev server), and as far as I can see the title and description of nested focus concepts are not available in the json output of the template parser.
Ie. : 
UI: https://postco.test-nictiz.nl/#/template/nictiz_beeldvormendeVerrichtingAanZijde_1605716520
Template: https://postco.test-nictiz.nl/templates/nictiz_beeldvormendeVerrichtingAanZijde_1605716520
XML: https://github.com/mertenssander/postco/blob/c74a113be26a774afb50617e1e196f62001abbec/SnomedTemplateService/SnomedTemplateService.Web/SnomedTemplates/nictiz/beeldvormendeVerrichtingAanZijde_1605716520.xml#L24

Do you know why this is happening, or was this one of the things we forgot to put on the to-do list?

Thanks! Sander

**Comment by basharmsen** [comment]
In the user interface space has been left for the titles and descriptions of both the focus concepts and the nested expressions. However, in the web service results model, title and description fields do not exist for focus concepts, only for nested expressions.

**Comment by mertenssander** [comment]
@basharmsen Could you add those in the relevant space?

**Comment by basharmsen** [comment]
I have changed the method to specify the description and title for a focus concept or attribute. The key in the slots dictionary now points to its target using an [information slot](https://confluence.ihtsdotools.org/display/DOCSTS/8.5.+Information+Slots).

For example the template expression for [Beeldvormende verrichting van locatie aan zijde](https://github.com/mertenssander/postco/blob/cf06cc337fac0ca7b5a20c24d3a4a608f77a8c4d/SnomedTemplateService/SnomedTemplateService.Web/SnomedTemplates/nictiz/beeldvormendeVerrichtingAanZijde_1605716520.xml) contains 4 information slots.
- The name Methode is used to refer to the 'methode' attribute (name-value-pair),
- Location is used for 'directe locatie van verrichting'. The value of this attribute is a nested expression.
- LocatieFocus is used for the focus concept of this nested expression.
- Laterality is used for the 'Laterality' attribute of the nested expression.

An information slot for an attribute in the expression should be placed just before the attribute name-value pair and for a focus concept it should be placed just before the focus concept.

Currently, for both the attribute and the focus concept of a nested expression, the UI uses the title/description of the attribute. Because of this, an attribute with a complex value currently uses the same title/description for the attribute and the focus concept.

**Comment by mertenssander** [comment]
@basharmsen I have just pulled and deployed this version to the server. Can you check if everything is functioning as intended? Do we need to change the templates? Does @hielkema need to know about this?

**Comment by basharmsen** [comment]
It seems to me that everything is functioning as intended. To also use the title/description of the focus concept instead of just the title/description of the attribute the UI should also be modified.
@hielkema At this moment the title and description of constant attributes are not used. Using the method described above it is also possible to specify title/description for constant attributes. And when the UI would be modified such that it also uses the title/description of the focus concepts then those should also be added.

**Comment by mertenssander** [comment]
Fixed with commit https://github.com/mertenssander/postco/commit/391c8531d9163fbf846440727a68310353e6fe61
