### ISSUE TITLE
Errors in templates - problem with communication with snowstorm?

### ISSUE THREAD

**Issue by piotrekwoznicki** [mertenssander/postco#39]
Hello,

I was actively looking for a tool to add new concepts/create postcoordinated expressions in SNOMED CT, and I think your project enabling the creation of postcoord exp from ETL templates is a very relevant tool. Very glad someone has been working on it!

I built and started the containers in development mode, and experimented firstly with the default snowstorm address, and then with a local snowstorm server. When I go to localhost:9124 and select any available template, I get a stack of errors, beginning with:
Er is een fout opgetreden bij het ophalen van een term. [focusConceptPrecoordinated]
Er is een fout opgetreden bij het ophalen van een term. [templateAttributeCompact]

Moreover, when I try to type in a term into the template, the search does not return any suggested concepts (the search does not finish either). When tested with the local snowstorm server, the server has no problem with addresses and apparently returns results from queries given while typing the term.
The containers are run without any errors, I get only a warning from templateservice: 
templateservice_1  | warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3].  Failed to determine the https port for redirect.

Do you have any idea how could this be fixed?

Best, Piotr

**Comment by mertenssander** [comment]
Hi @piotrekwoznicki ,
Great to hear that you've found our project! The error you're seeing is caused by the fact that the templates in the master branch look for a SNOMED version that is not present in our dev Snowstorm server (at the moment it only has a snapshot import of the latest release). If you use the development branch that should be fixed - I've pushed those to the latest SNOMED release. If you want to check out the tool without any management, you could go to postco.test-nictiz.nl, where we host an instance of the development branch. Of course: no guarantees on uptime on this server.

Alternatively, you could host your own snowstorm server and change every mention of snowstorm.test-nictiz.nl to your own snowstorm instance. At the moment there is no centralized place to change this address, that will be added in the future.

Hope this solves your issue, please let us know how you get on!

Regards, Sander

**Comment by mertenssander** [comment]
I have just merged the development branch to master, so pulling the changes to your machine and rebuilding/recreating the containers should do the trick as well.

**Comment by piotrekwoznicki** [comment]
Hi @mertenssander, 

thanks for such a quick fix. It works now with updated dates! 
I think at postco.test-nictiz.nl there's still one template, 'Medicinal product package', that's would show errors.
